include: https://raw.githubusercontent.com/hassio-addons/organization/master/gitlabci/addon.yml

variables:
  DOCKER_TLS_CERTDIR: ""

  ADDON_GITHUB_REPO: "nqkdev/hassio-addons"
  ADDON_SLUG: "octoprint_internal"
  ADDON_TARGET: "octoprint_internal"

  ADDON_PUBLISH: "false"
  DOCKER_HUB_ORG: nqkdev

  PREFLIGHT_HADOLINT: "false"
  PREFLIGHT_YAMLLINT: "false"
  PREFLIGHT_MARKDOWNLINT: "false"
  PREFLIGHT_JSONLINT: "true"
  PREFLIGHT_SHELLCHECK: "true"